vocabularies = \
{'bibliographic_source_values': [
    (u'bibliothekskataloge_literaturdatenbanken_und_fachbibliographien',
     u'Bibliothekskataloge, Literaturdatenbanken und Fachbibliographien'),
    (u'fachportale_und_linksammlungen', u'Fachportale und Linksammlungen'),
    (u'nachrichtenmedien', u'Nachrichtenmedien'),
    (u'sammlungen_gesetzes-_und_vertragstexte',
     u'Sammlungen, Gesetzes- und Vertragstexte'),
    (u'suchmaschinen_und_kataloge', u'Suchmaschinen und Kataloge'),
    (u'verzeichnisse_amtliche_literatur', u'Verzeichnisse, amtliche Literatur'),
    (u'verzeichnisse_arbeitspapiere_preprints',
     u'Verzeichnisse, Arbeitspapiere, Preprints'),
    (u'verzeichnisse_audio-visuelle_materialien_und_karten',
     u'Verzeichnisse, audio-visuelle Materialien und Karten'),
    (u'verzeichnisse_aufsaetze_e-books_u.a._volltexte',
     u'Verzeichnisse, Aufs\xe4tze, e-books u.a. Volltexte'),
    (u'verzeichnisse_dissertationen', u'Verzeichnisse, Dissertationen'),
    (u'verzeichnisse_fachzeitschriften_und_jahrbuecher',
     u'Verzeichnisse, Fachzeitschriften und Jahrb\xfccher'),
    (u'verzeichnisse_geschaefts-_und_jahresberichte',
     u'Verzeichnisse, Gesch\xe4fts- und Jahresberichte'),
    (u'verzeichnisse_individuelle_homepages',
     u'Verzeichnisse, individuelle Homepages'),
    (u'verzeichnisse_kongress-_und_tagungsbeitraege',
     u'Verzeichnisse, Kongress- und Tagungsbeitr\xe4ge'),
    (u'verzeichnisse_lehrmaterialien_und_einfuehrungen',
     u'Verzeichnisse, Lehrmaterialien und Einf\xfchrungen'),
    (u'verzeichnisse_newsletter_mailinglisten_foren_chats',
     u'Verzeichnisse, Newsletter, Mailinglisten, Foren, Chats'),
    (u'verzeichnisse_software', u'Verzeichnisse, Software'),
    (u'verzeichnisse_urteilsanmerkungen', u'Verzeichnisse, Urteilsanmerkungen'),
    (u'verzeichnisse_urteilstexte', u'Verzeichnisse, Urteilstexte'),
    (u'verzeichnisse_vertragsmuster_klage-_und_antragsmuster',
     u'Verzeichnisse, Vertragsmuster, Klage- und Antragsmuster'),
    (u'weitere_bibliographische_quellen', u'Weitere bibliographische Quellen'),
    ],
 'cooperations_and_communication_values': [
    (u'arbeitsgemeinschaften', u'Arbeitsgemeinschaften'),
    (u'forschungsprojekte', u'Forschungsprojekte'),
    (u'mailinglisten_foren_weblogs_chats',
     u'Mailinglisten, Foren, Weblogs, Chats'),
    (u'veranstaltungen', u'Veranstaltungen'),
    (u'weitere_kooperationsformen', u'Weitere Kooperationsformen')
    ],
 'individual_publication_values': [
    (u'amtliche_publikation', u'Amtliche Publikation'),
    (u'arbeitspapier_preprint', u'Arbeitspapier, Preprint'),
    (u'audio-visuelles_material_karte', u'Audio-visuelles Material, Karte'),
    (u'aufsatz', u'Aufsatz'),
    (u'dissertation', u'Dissertation'),
    (u'e-book_bericht_studie', u'e-book, Bericht, Studie'),
    (u'fachspezifische_software', u'Fachspezifische Software'),
    (u'fachzeitschrift_jahrbuch_mit_volltext',
     u'Fachzeitschrift/Jahrbuch (mit Volltext)'),
    (u'fachzeitschrift_jahrbuch_ohne_volltext',
     u'Fachzeitschrift/Jahrbuch (ohne Volltext)'),
    (u'gesetzes-_und_vertragstext', u'Gesetzes- und Vertragstext'),
    (u'individuelle_homepage', u'Individuelle Homepage'),
    (u'lehrmaterial_einfuehrung', u'Lehrmaterial, Einf\xfchrung'),
    (u'nachrichtenmedium', u'Nachrichtenmedium'),
    (u'newsletter', u'Newsletter'),
    (u'tagungsbeitrag', u'Tagungsbeitrag'),
    (u'thematische_website', u'Thematische Website'),
    (u'urteilsanmerkungen', u'Urteilsanmerkungen'),
    (u'urteilstext', u'Urteilstext'),
    (u'vertragsmuster_klage-_und_antragsmuster',
     u'Vertragsmuster, Klage- und Antragsmuster'),
    (u'weitere_publikationsarten', u'Weitere Publikationsarten')
    ],
 'institution_values': [
    (u'amtliche_koerperschaften_und_organisationen',
     u'Amtliche K\xf6rperschaften und Organisationen'),
    (u'bibliotheken_und_archive', u'Bibliotheken und Archive'),
    (u'fachgesellschaften_und_berufsverbaende',
     u'Fachgesellschaften und Berufsverb\xe4nde'),
    (u'hochschul-_und_forschungseinrichtungen',
     u'Hochschul- und Forschungseinrichtungen'),
    (u'internationale_organisationen', u'Internationale Organisationen'),
    (u'medien', u'Medien'),
    (u'nichtregierungsorganisationen', u'Nichtregierungsorganisationen'),
    (u'parteien_und_politische_organisationen',
     u'Parteien und politische Organisationen'),
    (u'public_private_partnership', u'Public Private Partnership'),
    (u'unternehmen', u'Unternehmen'),
    (u'verbaende', u'Verb\xe4nde'),
    (u'verlage_und_datenbankanbieter', u'Verlage und Datenbankanbieter'),
    (u'weitere_institutionen', u'Weitere Institutionen')
    ] ,
 'reference_values': [
    (u'abkuerzungswerke', u'Abk\xfcrzungswerke'),
    (u'anleitungen_und_handbuecher', u'Anleitungen und Handb\xfccher'),
    (u'datensammlungen_und_statistiken', u'Datensammlungen und Statistiken'),
    (u'gesetzeskommentare', u'Gesetzeskommentare'),
    (u'lexika', u'Lexika'),
    (u'laenderinformationen', u'L\xe4nderinformationen'),
    (u'normen_und_standards', u'Normen und Standards'),
    (u'sprachwoerterbuecher', u'Sprachw\xf6rterb\xfccher'),
    (u'tabellenwerke', u'Tabellenwerke'),
    (u'verzeichnisse_von_personen_unternehmen_und_institutionen',
     u'Verzeichnisse von Personen, Unternehmen und Institutionen'),
    (u'weitere_nachschlagewerke', u'Weitere Nachschlagewerke')
     ]
 }

languages = [u'sq',
             u'hy',
             u'az',
             u'bs',
             u'bg',
             u'ca',
             u'hr',
             u'cs',
             u'da',
             u'nl',
             u'en',
             u'et',
             u'fi',
             u'fr',
             u'ka',
             u'de',
             u'el',
             u'hu',
             u'it',
             u'lv',
             u'lt',
             u'no',
             u'pl',
             u'pt',
             u'ro',
             u'ru',
             u'sr',
             u'sk',
             u'sl',
             u'es',
             u'sv',
             u'tr',
             u'uk']

USER_LANGUAGES = [
        u'de',
        u'fr',
        u'en',
        ]
