# Dont import this file, its just for our i18n toolchain

from recensio.policy import recensioMessageFactory as _

_("About us")
_("Cut PDF")
_("Epoch")
_("Folder")
_("Import")
_("Issue")
_("Listen to audio for this captcha")
_("Pending review")
_("Pending")
_("Presentation Article Review")
_("Presentation Article edited Volume")
_("Presentation Article in Journal")
_("Presentation Collection")
_("Presentation Monograph")
_("Presentation Online Resource")
_("Private")
_("Publication")
_("Published")
_("Region")
_("Results per page")
_("Review Journal")
_("Review Monograph")
_("Review")
_("The number of results that is displayed on one page.")
_("Themes")
_("Topic")
_("articles")
_("browse_topics")
_("create_presentation")
_("description_presentation_article")
_("description_presentation_collection")
_("description_presentation_monograph")
_("description_presentation_online_resource")
_("label_by_author")
_("label_participate")
_("label_presentations")
_("label_press")
_("label_reviews")
_("label_schema_presented_text")
_("label_schema_review")
_("label_schema_reviewed_text")
_("license-note")
_("manage_presentations")
_("monographs")
_("new_discussions")
_("new_presentations")
_("new_reviews")
_("online_resources")
_("participating_in_recensio_net")
_("presentations")
_("presented resource")
_("register_and_create_presentations")
_("reviews")
_("rss_feeds")
_("text_in")
_("text_pages")
_("text_presentation_of")
_("text_review_of")
_("title_presentation_monograph")
