# Dont import this file, its just for our i18n toolchain

from recensio.policy import recensioMessageFactory as _

_("license-note")
_("text_presentation_of")
_("text_in")
_("text_pages")
_("text_review_of")
_("presented resource")
_("label_by_author")
_("Issue")
_("Publication")
_("Results per page")
_("The number of results that is displayed on one page.")
_("label_reviews")
_("label_presentations")
_("label_participate")
_("label_press")
_("Import")
_("Cut PDF")
_("Themes")
_("About us")
_("Review")
_("title_presentation_monograph")
_("description_presentation_monograph")
_("Presentation Online Resource")
_("Presentation Article Review")
_("Presentation Collection")
_("Presentation Monograph")
_("Review Journal")
_("Review Monograph")
_("Epoch")
_("Region")
_("Topic")
_("Pending")
_("Pending review")
_("Private")
_("Published")
_("Folder")
_("Listen to audio for this captcha")
_("Presentation Article in Journal")
_("Presentation Article edited Volume")
_("label_schema_review")
_("label_schema_reviewed_text")
_("label_schema_presented_text")
_("description_presentation_monograph")
_("description_presentation_collection")
_("description_presentation_online_resource")
_("description_presentation_article")
_("license-note")
_("text_presentation_of")
_("text_in")
_("text_pages")
_("text_review_of")
_("label_reviews")
_("label_presentations")
_("label_participate")
_("label_press")
_("Import")
_("Cut PDF")
_("Themes")
_("About us")
_("description_presentation_monograph")
_("Presentation Collection")
_("label_schema_review")
_("description_presentation_monograph")
_("description_presentation_collection")
_("description_presentation_online_resource")
_("description_presentation_article")
_("text_presentation_of")
_("text_in")
_("text_pages")
_("text_review_of")
_("label_reviews")
_("label_presentations")
_("label_participate")
_("label_press")
_("Albanian")
_("Armenian")
_("Azerbaijani")
_("Bulgarian")
_("Catalan")
_("Croatian")
_("Czech")
_("Danish")
_("Dutch")
_("English")
_("Estonian")
_("Finnish")
_("French")
_("Georgian")
_("German")
_("Greek")
_("Hungarian")
_("Italian")
_("Latvian")
_("Lithuanian")
_("Norwegian")
_("Polish")
_("Portuguese")
_("Romanian")
_("Russian")
_("Serbian")
_("Slovak")
_("Slovenian")
_("Spanish")
_("Swedish")
_("Turkish")
_("Ukrainian")

